<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UserLoginWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/UserFolder/UserLoginWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/UserFolder/UserLoginWSDL" xmlns:ns="http://userws.potatoni.com/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/UserFolder/UserLoginWSDL">
            <xsd:import namespace="http://userws.potatoni.com/" schemaLocation="http://192.168.1.110:9999/ServiceLayer/UserWebService?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="UserLoginWSDLOperationRequest">
        <part name="inputUserLogin" element="ns:logIn"/>
    </message>
    <message name="UserLoginWSDLOperationResponse">
        <part name="outputUserLogin" element="ns:logInResponse"/>
    </message>
    <portType name="UserLoginWSDLPortType">
        <operation name="UserLoginWSDLOperation">
            <input name="input1" message="tns:UserLoginWSDLOperationRequest"/>
            <output name="output1" message="tns:UserLoginWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="UserLoginWSDLBinding" type="tns:UserLoginWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="UserLoginWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="UserLoginWSDLService">
        <port name="UserLoginWSDLPort" binding="tns:UserLoginWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/UserLoginWSDLService/UserLoginWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="UserLoginWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="UserLoginWSDLPortTypeRole" portType="tns:UserLoginWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
