<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BidGetAllCustomerWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/BidFolder/BidGetAllCustomerWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/BidFolder/BidGetAllCustomerWSDL" xmlns:ns="http://bidws.potatoni.org/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/BidFolder/BidGetAllCustomerWSDL">
            <xsd:import namespace="http://bidws.potatoni.org/" schemaLocation="http://192.168.1.110:9999/ServiceLayer/BidWebService?xsd=1"/>
        </xsd:schema>
    </types>
    <message name="BidGetAllCustomerWSDLOperationRequest">
        <part name="input" element="ns:getAllCustomers"/>
    </message>
    <message name="BidGetAllCustomerWSDLOperationResponse">
        <part name="output" element="ns:getAllCustomersResponse"/>
    </message>
    <portType name="BidGetAllCustomerWSDLPortType">
        <operation name="BidGetAllCustomerWSDLOperation">
            <input name="input1" message="tns:BidGetAllCustomerWSDLOperationRequest"/>
            <output name="output1" message="tns:BidGetAllCustomerWSDLOperationResponse"/>
        </operation>
    </portType>
    <binding name="BidGetAllCustomerWSDLBinding" type="tns:BidGetAllCustomerWSDLPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="BidGetAllCustomerWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="BidGetAllCustomerWSDLService">
        <port name="BidGetAllCustomerWSDLPort" binding="tns:BidGetAllCustomerWSDLBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/BidGetAllCustomerWSDLService/BidGetAllCustomerWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="BidGetAllCustomerWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="BidGetAllCustomerWSDLPortTypeRole" portType="tns:BidGetAllCustomerWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
