<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BidWebServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/BidWebServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/BidWebServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://bidws.potatoni.org/">
    <import location="http://192.168.1.110:9999/ServiceLayer/BidWebService?wsdl" namespace="http://bidws.potatoni.org/"/>
    <plnk:partnerLinkType name="BidWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="BidGetHighestPriceWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="BidGetAllBidsWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="BidBookWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="BidBidBookWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
    <plnk:partnerLinkType name="BidGetAllCustomersWebServiceLinkType">
        <plnk:role name="BidWebServiceRole" portType="ns:BidWebService"/>
    </plnk:partnerLinkType>
</definitions>
