<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OrderWebServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/OrderWebServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/OrderWebServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://orderws.potatoni.com/">
    <import location="http://192.168.1.110:9999/ServiceLayer/OrderWebService?wsdl" namespace="http://orderws.potatoni.com/"/>
    <plnk:partnerLinkType name="OrderWebServiceLinkType">
        <plnk:role name="OrderWebServiceRole" portType="ns:OrderWebService"/>
    </plnk:partnerLinkType>
</definitions>
