<definitions name="SendingEmail" targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/EmailSystem/SendingEmail"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:jms="http://schemas.sun.com/jbi/wsdl-extensions/jms/" xmlns:tns="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/EmailSystem/SendingEmail" xmlns:ns="http://www.potatoni.com/mailsystem/emailentity" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/YBandMB_BPEL/EmailSystem/SendingEmail">
            <xsd:import namespace="http://www.potatoni.com/mailsystem/emailentity" schemaLocation="EmailEntitySchema1.xsd"/>
        </xsd:schema>
    </types>
    <message name="JMSInputMessage">
        <part name="part1" type="ns:EmailEntityComplexType"/>
    </message>  
    <portType name="JMSOutPortType">
        <operation name="JMSOutOperation">
            <input name="input1" message="tns:JMSInputMessage"/>
        </operation>
    </portType>
    <binding name="JMSOutBinding" type="tns:JMSOutPortType">
        <jms:binding/>
        <operation name="JMSOutOperation">
            <jms:operation destination="sendingEmailQueue" destinationType="Queue" transaction="NoTransaction" deliveryMode="PERSISTENT" priority="4" timeout="300000"/>
            <input name="input1">
                <jms:message messageType="TextMessage" textPart="part1"/>
            </input>
        </operation>
    </binding>
    <service name="JMSOutService">
        <port name="SendingEmail_OutPort" binding="tns:JMSOutBinding">
            <jms:address connectionURL="mq://192.168.1.110:7676" username="admin" password="admin">
                <jms:jmsjcaOptions><![CDATA[]]></jms:jmsjcaOptions>
            </jms:address>
        </port>
    </service>
    <plnk:partnerLinkType name="SendingEmail">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="JMSOutPortTypeRole" portType="tns:JMSOutPortType"/>
    </plnk:partnerLinkType>
</definitions>
